apiVersion: apps/v1
kind: Deployment
metadata:
  name: tms-demo-enrichment
  namespace: tms-demo
  labels:
    app: tms-demo-enrichment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tms-demo-enrichment
  template:
    metadata:
      labels:
        app: tms-demo-enrichment
    spec:
      containers:      
      - name: tms-demo-enrichment
        image: ssaily/tms-demo-processing:0.2.0
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: enrichment
        envFrom:
          - secretRef:
              name: kafka-secrets        
          - secretRef: 
              name: tms-service-endpoint
        volumeMounts:
        - mountPath: /etc/streams/tms-processing-cert
          name: tms-processing-cert
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "100m"
        imagePullPolicy: Always
      volumes:
        - name: tms-processing-cert
          secret:
            secretName: tms-processing-cert
            items:
            - key: client.keystore.p12
              path: client.keystore.p12
            - key: client.truststore.jks
              path: client.truststore.jks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tms-demo-calculations
  namespace: tms-demo
  labels:
    app: tms-demo-calculations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tms-demo-calculations
  template:
    metadata:
      labels:
        app: tms-demo-calculations
    spec:
      containers:      
      - name: tms-demo-calculations
        image: ssaily/tms-demo-processing:0.2.0
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: calculations
        envFrom:
          - secretRef:
              name: kafka-secrets        
          - secretRef: 
              name: tms-service-endpoint
        volumeMounts:
        - mountPath: /etc/streams/tms-processing-cert
          name: tms-processing-cert
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "100m"
        imagePullPolicy: Always      
      volumes:
        - name: tms-processing-cert
          secret:
            secretName: tms-processing-cert
            items:
            - key: client.keystore.p12
              path: client.keystore.p12
            - key: client.truststore.jks
              path: client.truststore.jks
