# With SSL configured
spring:
    application:
      name: tms-streams-demo-${SPRING_PROFILES_ACTIVE}
      schema-registry: ${SCHEMA_REGISTRY}      
    kafka:
      bootstrap-servers: ${BOOTSTRAP_SERVERS}      
      ssl:
        truststore-location: file:/etc/streams/tms-processing-cert/client.truststore.jks
        truststore-password: ${truststore-password}
        truststore-type: JKS
        keystore-location: file:/etc/streams/tms-processing-cert/client.keystore.p12
        keystore-password: ${keystore-password}
        keystore-type: PKCS12
        key-password: ${key-password}
      properties:
        security.protocol: SSL